//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.02 at 10:21:23 PM EDT 
//


package nsu.msit665.flight.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for FlightAvailabilityRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightAvailabilityRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Origin" type="{http://example.com/flight}LocationCodeType"/&gt;
 *         &lt;element name="Destination" type="{http://example.com/flight}LocationCodeType"/&gt;
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Passengers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Passenger" type="{http://example.com/flight}PassengerCountType" maxOccurs="3"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TimeRange" type="{http://example.com/flight}TimeRangeType" minOccurs="0"/&gt;
 *         &lt;element name="PreferredConnectingCities" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ConnectingCity" type="{http://example.com/flight}LocationCodeType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PreferredAirlines" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AirlineCode" type="{http://example.com/flight}AirlineCodeType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FlightTypes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="FlightType" type="{http://example.com/flight}FlightTypeEnum" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SpecificAirline" type="{http://example.com/flight}AirlineCodeType" minOccurs="0"/&gt;
 *         &lt;element name="SpecificFlight" type="{http://example.com/flight}SpecificFlightType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightAvailabilityRequestType", namespace = "http://example.com/flight", propOrder = {
    "origin",
    "destination",
    "departureDate",
    "passengers",
    "timeRange",
    "preferredConnectingCities",
    "preferredAirlines",
    "flightTypes",
    "specificAirline",
    "specificFlight"
})
@XmlRootElement(name = "FlightAvailabilityRequestType", namespace = "http://example.com/flight/ws")
public class FlightAvailabilityRequestType {

    @XmlElement(name = "Origin", namespace = "http://example.com/flight", required = true)
    protected String origin;
    @XmlElement(name = "Destination", namespace = "http://example.com/flight", required = true)
    protected String destination;
    @XmlElement(name = "DepartureDate", namespace = "http://example.com/flight", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    @XmlElement(name = "Passengers", namespace = "http://example.com/flight", required = true)
    protected FlightAvailabilityRequestType.Passengers passengers;
    @XmlElement(name = "TimeRange", namespace = "http://example.com/flight")
    protected TimeRangeType timeRange;
    @XmlElement(name = "PreferredConnectingCities", namespace = "http://example.com/flight")
    protected FlightAvailabilityRequestType.PreferredConnectingCities preferredConnectingCities;
    @XmlElement(name = "PreferredAirlines", namespace = "http://example.com/flight")
    protected FlightAvailabilityRequestType.PreferredAirlines preferredAirlines;
    @XmlElement(name = "FlightTypes", namespace = "http://example.com/flight")
    protected FlightAvailabilityRequestType.FlightTypes flightTypes;
    @XmlElement(name = "SpecificAirline", namespace = "http://example.com/flight")
    protected String specificAirline;
    @XmlElement(name = "SpecificFlight", namespace = "http://example.com/flight")
    protected SpecificFlightType specificFlight;

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * @return
     *     possible object is
     *     {@link FlightAvailabilityRequestType.Passengers }
     *     
     */
    public FlightAvailabilityRequestType.Passengers getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightAvailabilityRequestType.Passengers }
     *     
     */
    public void setPassengers(FlightAvailabilityRequestType.Passengers value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the timeRange property.
     * 
     * @return
     *     possible object is
     *     {@link TimeRangeType }
     *     
     */
    public TimeRangeType getTimeRange() {
        return timeRange;
    }

    /**
     * Sets the value of the timeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeRangeType }
     *     
     */
    public void setTimeRange(TimeRangeType value) {
        this.timeRange = value;
    }

    /**
     * Gets the value of the preferredConnectingCities property.
     * 
     * @return
     *     possible object is
     *     {@link FlightAvailabilityRequestType.PreferredConnectingCities }
     *     
     */
    public FlightAvailabilityRequestType.PreferredConnectingCities getPreferredConnectingCities() {
        return preferredConnectingCities;
    }

    /**
     * Sets the value of the preferredConnectingCities property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightAvailabilityRequestType.PreferredConnectingCities }
     *     
     */
    public void setPreferredConnectingCities(FlightAvailabilityRequestType.PreferredConnectingCities value) {
        this.preferredConnectingCities = value;
    }

    /**
     * Gets the value of the preferredAirlines property.
     * 
     * @return
     *     possible object is
     *     {@link FlightAvailabilityRequestType.PreferredAirlines }
     *     
     */
    public FlightAvailabilityRequestType.PreferredAirlines getPreferredAirlines() {
        return preferredAirlines;
    }

    /**
     * Sets the value of the preferredAirlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightAvailabilityRequestType.PreferredAirlines }
     *     
     */
    public void setPreferredAirlines(FlightAvailabilityRequestType.PreferredAirlines value) {
        this.preferredAirlines = value;
    }

    /**
     * Gets the value of the flightTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FlightAvailabilityRequestType.FlightTypes }
     *     
     */
    public FlightAvailabilityRequestType.FlightTypes getFlightTypes() {
        return flightTypes;
    }

    /**
     * Sets the value of the flightTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightAvailabilityRequestType.FlightTypes }
     *     
     */
    public void setFlightTypes(FlightAvailabilityRequestType.FlightTypes value) {
        this.flightTypes = value;
    }

    /**
     * Gets the value of the specificAirline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificAirline() {
        return specificAirline;
    }

    /**
     * Sets the value of the specificAirline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificAirline(String value) {
        this.specificAirline = value;
    }

    /**
     * Gets the value of the specificFlight property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificFlightType }
     *     
     */
    public SpecificFlightType getSpecificFlight() {
        return specificFlight;
    }

    /**
     * Sets the value of the specificFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificFlightType }
     *     
     */
    public void setSpecificFlight(SpecificFlightType value) {
        this.specificFlight = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="FlightType" type="{http://example.com/flight}FlightTypeEnum" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flightType"
    })
    public static class FlightTypes {

        @XmlElement(name = "FlightType", namespace = "http://example.com/flight", required = true)
        @XmlSchemaType(name = "string")
        protected List<FlightTypeEnum> flightType;

        /**
         * Gets the value of the flightType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the flightType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlightType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightTypeEnum }
         * 
         * 
         */
        public List<FlightTypeEnum> getFlightType() {
            if (flightType == null) {
                flightType = new ArrayList<FlightTypeEnum>();
            }
            return this.flightType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Passenger" type="{http://example.com/flight}PassengerCountType" maxOccurs="3"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passenger"
    })
    public static class Passengers {

        @XmlElement(name = "Passenger", namespace = "http://example.com/flight", required = true)
        protected List<PassengerCountType> passenger;

        /**
         * Gets the value of the passenger property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the passenger property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassenger().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassengerCountType }
         * 
         * 
         */
        public List<PassengerCountType> getPassenger() {
            if (passenger == null) {
                passenger = new ArrayList<PassengerCountType>();
            }
            return this.passenger;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AirlineCode" type="{http://example.com/flight}AirlineCodeType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airlineCode"
    })
    public static class PreferredAirlines {

        @XmlElement(name = "AirlineCode", namespace = "http://example.com/flight", required = true)
        protected List<String> airlineCode;

        /**
         * Gets the value of the airlineCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the airlineCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAirlineCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAirlineCode() {
            if (airlineCode == null) {
                airlineCode = new ArrayList<String>();
            }
            return this.airlineCode;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ConnectingCity" type="{http://example.com/flight}LocationCodeType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connectingCity"
    })
    public static class PreferredConnectingCities {

        @XmlElement(name = "ConnectingCity", namespace = "http://example.com/flight", required = true)
        protected List<String> connectingCity;

        /**
         * Gets the value of the connectingCity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the connectingCity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnectingCity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getConnectingCity() {
            if (connectingCity == null) {
                connectingCity = new ArrayList<String>();
            }
            return this.connectingCity;
        }

    }

}
