//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.02 at 10:21:23 PM EDT 
//


package nsu.msit665.flight.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FlightTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NonStop"/&gt;
 *     &lt;enumeration value="OneStop"/&gt;
 *     &lt;enumeration value="MultiStop"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FlightTypeEnum", namespace = "http://example.com/flight")
@XmlEnum
public enum FlightTypeEnum {

    @XmlEnumValue("NonStop")
    NON_STOP("NonStop"),
    @XmlEnumValue("OneStop")
    ONE_STOP("OneStop"),
    @XmlEnumValue("MultiStop")
    MULTI_STOP("MultiStop");
    private final String value;

    FlightTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FlightTypeEnum fromValue(String v) {
        for (FlightTypeEnum c: FlightTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
