//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.03 at 11:09:42 PM EDT 
//


package nsu.msit665.flight.model;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nsu.msit665.flight.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlightAvailabilityRequest_QNAME = new QName("http://example.com/flight", "FlightAvailabilityRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nsu.msit665.flight.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightAvailabilityRequestType }
     * 
     */
    public FlightAvailabilityRequestType createFlightAvailabilityRequestType() {
        return new FlightAvailabilityRequestType();
    }

    /**
     * Create an instance of {@link PassengerCountType }
     * 
     */
    public PassengerCountType createPassengerCountType() {
        return new PassengerCountType();
    }

    /**
     * Create an instance of {@link TimeRangeType }
     * 
     */
    public TimeRangeType createTimeRangeType() {
        return new TimeRangeType();
    }

    /**
     * Create an instance of {@link SpecificFlightType }
     * 
     */
    public SpecificFlightType createSpecificFlightType() {
        return new SpecificFlightType();
    }

    /**
     * Create an instance of {@link FlightAvailabilityRequestType.Passengers }
     * 
     */
    public FlightAvailabilityRequestType.Passengers createFlightAvailabilityRequestTypePassengers() {
        return new FlightAvailabilityRequestType.Passengers();
    }

    /**
     * Create an instance of {@link FlightAvailabilityRequestType.PreferredConnectingCities }
     * 
     */
    public FlightAvailabilityRequestType.PreferredConnectingCities createFlightAvailabilityRequestTypePreferredConnectingCities() {
        return new FlightAvailabilityRequestType.PreferredConnectingCities();
    }

    /**
     * Create an instance of {@link FlightAvailabilityRequestType.PreferredAirlines }
     * 
     */
    public FlightAvailabilityRequestType.PreferredAirlines createFlightAvailabilityRequestTypePreferredAirlines() {
        return new FlightAvailabilityRequestType.PreferredAirlines();
    }

    /**
     * Create an instance of {@link FlightAvailabilityRequestType.FlightTypes }
     * 
     */
    public FlightAvailabilityRequestType.FlightTypes createFlightAvailabilityRequestTypeFlightTypes() {
        return new FlightAvailabilityRequestType.FlightTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightAvailabilityRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FlightAvailabilityRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.com/flight", name = "FlightAvailabilityRequest")
    public JAXBElement<FlightAvailabilityRequestType> createFlightAvailabilityRequest(FlightAvailabilityRequestType value) {
        return new JAXBElement<FlightAvailabilityRequestType>(_FlightAvailabilityRequest_QNAME, FlightAvailabilityRequestType.class, null, value);
    }

}
