//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.02 at 10:21:23 PM EDT 
//


package nsu.msit665.flight.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassengerTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PassengerTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADT"/&gt;
 *     &lt;enumeration value="CHD"/&gt;
 *     &lt;enumeration value="INF"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PassengerTypeEnum", namespace = "http://example.com/flight")
@XmlEnum
public enum PassengerTypeEnum {

    ADT,
    CHD,
    INF;

    public String value() {
        return name();
    }

    public static PassengerTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
